<a href="https://colab.research.google.com/github/SpandanM110/Python-and-it-s-Libraries/blob/main/Numpy_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# NUMPY TYPES

In [ ]:
import numpy as np
dt= np.dtype(np.int32)
print(dt)

int32


In [ ]:
#int8,#int16, #int32, #int64 are equivalent to i1,i2,i4,i8

dt = np.dtype('i4')
print(dt)

int32


In [ ]:
#using endion notation

dt = np.dtype('>i4')
print(dt)

>i4


In [ ]:
dt = np.dtype([('age',np.int8)])  # * bit integer type array
print(dt)

[('age', 'i1')]


In [ ]:
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)], dtype=dt)
print(a)

[(10,) (20,) (30,)]


# NUMPY ARRAYS

In [ ]:
a=np.array([1,2,3]) #1D Array
print(a)

[1 2 3]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])  #2D Array
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
#min dimensions
a=np.array([1,2,3,4,5], ndmin=2) #inorder to make it 2D
print(a)

[[1 2 3 4 5]]


In [ ]:
#dtype parameter
a=np.array([1,2,3], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


# NUMPY ARRAY ATTRIBUTES

In [ ]:
import numpy as np
#ndarray.shape
a=np.array([[1,2,3],[4,5,6],[7,9,9]])
print(a.shape)
print(a)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 9 9]]


In [ ]:
#reshaping
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#ndimensions.ndim

a=np.array(24)
print(a)

b=np.arange(24)
print(b)
print(a.ndim) #no.of dimensions

24
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
0


In [ ]:
a=np.arange(24)
b=a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [ ]:
#numpy.itemsize
x=np.array([1,2,3,4,5], dtype=np.int8)
print(x)

print(x.itemsize)


#if 8 byte itemsize is 1
#if 16 byte itemsize is 2
#if 32 byte itemsize is 4
#if 64 byte itemsize is 8

[1 2 3 4 5]
1


# Numpy Math

In [ ]:
import numpy as np
import math as m

In [ ]:
m.sqrt(9)

3.0

In [ ]:
m.floor(7.3)

7

In [ ]:
m.ceil(9.2)

10

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=((a-b)**2).sum()
m.sqrt(c)

5.196152422706632

# Numpy Operations

In [ ]:
a=np.array([1,2,3])
b=np.array([3,8,7])
print(a+2)
print(a+b)
print(a**b)
print(a.mean())
print(a.sum())

[3 4 5]
[ 4 10 10]
[   1  256 2187]
2.0
6
